### ISSUE TITLE
Creating gradle plugin for GMetrics

### ISSUE THREAD

**Issue by shehabic-work** [dx42/gmetrics#13]
Hi there, I'm trying to execute the gmetrics ant task from within a Gradle Task for code-quality plugin that I'm writing but I'm stuck in there could you may be help, more details are there: 
https://stackoverflow.com/questions/48301719/how-to-run-ant-task-from-within-gradle-java-plugin-and-a-java-task

**Comment by chrismair** [comment]
Looking at the referenced Stackoverflow issue, it looks like  this was resolved.
